{{- if .Values.global.gossipEncryption.autoGenerate }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "consul.fullname" . }}-gossip-encryption-autogen
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups: [""]
  resources:
    - secrets
  verbs:
    - create
    - update
    - get
    - list
{{- if .Values.global.enablePodSecurityPolicies }}
- apiGroups: ["policy"]
  resources:
  - podsecuritypolicies
  verbs:
    - use
  resourceNames:
    - {{ template "consul.fullname" . }}-gossip-encryption-autogen
{{- end }}
{{- end }}
